<div class="block">

	<div class="block-head">
		<h2>Analytics</h2>
	</div>

	<div class="block-content">

		<div class="tabbable tabs-left">
			<ul class="nav nav-tabs">
                <li class="active"><a href="#lA" data-toggle="tab">Google Analytics</a></li>
                <li><a href="#lB" data-toggle="tab">Statistics</a></li>
                <li><a href="#lC" data-toggle="tab">Dummy page</a></li>
			</ul>
			<div class="tab-content">
				<!--
	
					Google Analytics

				-->
                <div class="tab-pane active" id="lA">
					
					<div class="alert alert-info">
						Your tracking code can be found in your Google Analytics
						panel Admin -> Tracking Code
					</div>
					
					<form class="form-horizontal">
						<div class="control-group">
							<label class="control-label" for="inputEmail">Tracking code</label>
							<div class="controls">
								<input type="text" id="inputEmail" placeholder="UA-XXXXXXXX-X">
							</div>
						</div>
						<div class="control-group">
							<div class="controls">
								<button type="submit" class="btn">Save settings</button>
							</div>
						</div>
					</form>	


                </div>
                <div class="tab-pane" id="lB">
					<p>Statistics coming soon...</p>
                </div>
                <div class="tab-pane" id="lC">
					<p>Dummy page</p>
                </div>
			</div>
		</div>

	</div>

</div>